### ISSUE TITLE
How to use in .js files?

### ISSUE THREAD

**Issue by wlingke** [mattberkowitz/autoclose-html#161]
I am writing some jsx tags in a .js file in Atom. However, they are not auto-closing. Is this feature available yet? If so, how do I enable it/get it to work? Thanks for the help!!

**Comment by klindroos** [comment]
Same problem here :)

**Comment by wlingke** [comment]
I forget what I did but if memory serves, the react package takes care of this

**Comment by mpacer** [comment]
This is still an issue for me and feels like it shouldn't be closed since there's no documented way to fix this.

**Comment by stelonix** [comment]
Same issue here, plugin is useless in .js files.

**Comment by carnigian** [comment]
I don't agree that the react package takes care of this, because the react package handles closing tags differently.

For example, the react package auto-closes, but does not add a newline, nor does it indent when I manually press return.

So in short, with the react package alone, I have to press return + tab for every tag.
