### ISSUE TITLE
Repeated Closing Tags

### ISSUE THREAD

**Issue by NarongSaron** [mattberkowitz/autoclose-html#52]
When I hit backspace one too many and accidentally remove the > in the opening tag, typing it creates another closing tag, even if there's an existing one. I guess this requires parsing the entire document also.

**Comment by mattberkowitz** [comment]
I started writing another plugin that had more of an awareness of the HTML document as a whole with the goal of using it to enable a lot of different features. Turns out it's a really tricky problem, and I still haven't fully figured things out (plus I don't have a ton of free time to invest in it right now). It's especially hard when you start looking at situations where the user might be doing something wrong, ie overlapping closing tags (<span><div></span></div>), has incomplete tags (<div <span>), etc

**Comment by stijnsanders** [comment]
could this be related to this pull request I just did? https://github.com/mattberkowitz/autoclose-html/pull/56

**Comment by MaxGiting** [comment]
![auto complete](https://cloud.githubusercontent.com/assets/9828591/6791126/b78ee02c-d1a4-11e4-955c-0241b5865284.gif)

I have a similar issue when using Smarty templating. I found pull request #56 fixed this!

**Comment by mattberkowitz** [comment]
I believe that this is resolved with 0.18.0, see #69
